# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'utf-8'

# Website info
name: '데이터공작소'
description: "데이터 분석은 잘 못하지만, 데이터 분석할 수 있게 도와드리겠어요!"

author: "drakejin"



google_analytics: UA-90708702-1
# Disque
disqus: drake-jin-github-io # ex. httpdongchuangithubio

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /
url: blog.drakejin.me


# Permalinks
permalink: /:title
# post의 category 또는 categories 에 의해서 author가 생성된다. 뭔 개같은 경우지?
#permalink: /author/:username
# permalink: /categories/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: drake-jin
repo: drake-jin.github.io
branch: master
relative_source: ../drake-jin.github.io
destination: ../drake-jin.github.io
production_url:  https://drake-jin.github.io/
source_url:      https://github.com/drake-jin/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - run
  - docs
